### ISSUE TITLE
Failed to start transaction, no context

### ISSUE THREAD

**Issue by dlanderson** [scoutapp/scout_apm_node#188] opened 2020-03-31 21:59 UTC
A user is seeing this in Express 4.17.1. They are also using Sentry.

![express error](https://user-images.githubusercontent.com/102774/78079022-81d16c00-7368-11ea-82cb-1630b677a88f.png)

Their config looks ok.

**Comment by vados-scout** [comment] 2020-04-06 05:23
I posted this also in the Slack but could you get their node version as well? Would like to try and reproduce as much of their env as possible (not sure if having Sentry is affecting it), and I can get a basic example up if I know which version of node & express they're using

**Comment by dlanderson** [comment] 2020-04-06 19:31
Node version 12.16

**Comment by vados-scout** [comment] 2020-04-07 15:05
Hey @dlanderson I made a copy of the nodejs testing code we've been passing around and switched to Node version 12.16.1 (I assume this was the correct semver) and express 4.17.1 and I can't reproduce this failure. The server [started up and sent a trace](https://scoutapm.com/apps/128634/endpoints/Q29udHJvbGxlci9HRVQgL3NxbF9wcm9taXNlX2FsbA==/trace/598759681).

I'm going to try and use it with sentry, does scout happen to have a sentry account lying around I could use to get closer to the environment?

**Comment by dlanderson** [comment] 2020-04-07 15:41
👍 for adding language version. We do use Sentry, but they also have a free developer tier which I would recommend to use.

**Comment by vados-scout** [comment] 2020-06-15 13:54
Hey @dlanderson could you get this client to update to v0.1.9? This should have been fixed.

**Comment by vados-scout** [comment] 2020-06-26 04:50
Closing this for now, it doesn't seem to be an issue anymore -- v0.1.10 is also already out

**Closed by vados-scout** 2020-06-26 04:50 UTC
Labels: bug, integration/express, node-internals
