### ISSUE TITLE
Avoid failing on windows

### ISSUE THREAD

**Issue by cschneid** [scoutapp/scout_apm_node#187] opened 2020-03-26 18:04 UTC
While we don't currently support windows, we want to be sure that we don't crash people's code by simply being present.

Currently we are raising a 'unknown triple' error, preventing a user's server from even starting. We should detect windows, log a polite error message and then be silent.

**Comment by C0ZEN** [comment] 2020-03-26 18:12
I can provide more information if needed.
I am unable to use scout for now on my Express project 😢

**Comment by vados-scout** [comment] 2020-04-06 05:28
Will look into this, and make sure the unknown triple error doesn't cause an app-stopping error. While the agent obviously won't be able to do anything on an unsupported platform I'll make sure it doesn't stop the app from starting up and errors a bit more quietly.

**Comment by vados-scout** [comment] 2020-04-07 15:26
Re-opening -- @C0ZEN would you mind trying this fix once a version is released? Likely when the `0.1.9` release has been cut?

**Comment by C0ZEN** [comment] 2020-04-07 16:56
@vados-scout yes of course

**Comment by vados-scout** [comment] 2020-05-22 12:58
Hey @C0ZEN thank you for your patience! Would you mind trying this new version: `npm i @scout_apm/scout-apm@0.1.9-rc.0`. I wanted to try it myself, and I've just confirmed that a simple test app does indeed start up without errors.

Of course, you're likely not going to get proper traces since scout does not yet support windows but your app should not crash because of this requirement, and once we do support windows you'll be ready to go.

**Comment by C0ZEN** [comment] 2020-05-22 13:09
@vados-scout I will give it a try this weekend.

**Comment by C0ZEN** [comment] 2020-05-22 14:02
@vados-scout seems good to me. Thanks.

**Comment by vados-scout** [comment] 2020-05-22 14:04
No problem @C0ZEN, thank you for the report! Please feel free to revert the versions for now, and once 0.1.9 is officially out I will close this ticket and tag you one more time

**Comment by vados-scout** [comment] 2020-05-31 14:48
Hi @C0ZEN -- v0.1.9 has just been released and should be available for use (with this fix inside)

**Closed by vados-scout** 2020-05-31 14:48 UTC
Labels: bug, needs-uat, platform/windows

**Comment by C0ZEN** [comment] 2020-05-31 15:39
Can close https://github.com/Sonia-corporation/il-est-midi-discord/pull/437.
